version: '3.2'

services:

  agent:
    image: portainer/agent:2.6.3
    container_name: portainer_agent
    security_opt:
      - no-new-privileges:true
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      - "${PORTAINER_AGENT_PORT}:9001"
