version: '2'

services:
      
  # DATABASES    
  mariadb:
    image: mariadb
    container_name: ${PROJECT_NAME}_mariadb
    restart: always
    command: --max_allowed_packet=256M
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${MYSQL_DATA_DIR}:/var/lib/mysql
      - ./mysql_logs/mysql/:/var/log/mysql
    networks:
      - internal

  nginx:
    image: nginx:latest
    container_name: ${PROJECT_NAME}_nginx
    restart: always
    ports:
        - "${NGINX_PORT}:80"
    volumes:
        - ${WWW_DATA_DIR}:/var/www/html
        - ./nginx:/etc/nginx/conf.d/
        - ./nginx_logs/nginx/:/var/log/nginx/
    links:
        - php
    networks:
      - internal

  php:
    build: .
    image: php:${PHP_VERSION}-fpm
    container_name: ${PROJECT_NAME}_php
    restart: always
    volumes:
      - ${WWW_DATA_DIR}:/var/www/html
      - ./php_logs/php/:/var/log/php
    networks:
      - internal

    # WP-CLI
    wordpress-cli:
        container_name: ${PROJECT_NAME}_wpcli
        depends_on:
        - mysql
        - wordpress
        image: wordpress:cli
        # vstm: This is required to run wordpress-cli with the same user-id as wordpress. 
        user: xfs
        # vstm: add shared volume
        volumes:
        - ${WWW_DATA_DIR}:/var/www/html

    # REDIS
    wpredis:
        container_name: ${PROJECT_NAME}_redis
        image: redis:6
        restart: unless-stopped
        volumes:
            - ${REDIS_DATA}:/data
        networks:
            - internal
        
#  # PHPMYADMIN
#  phpmyadmin:
#    container_name: ${PROJECT_NAME}_phpmyadmin
#    image: phpmyadmin/phpmyadmin
#    ports:
#      - 9880:80
#    hostname: ${PHPMYADMIN_DOMAIN}
#    environment:
#      PMA_HOST: mariadb
#    restart: always
#    volumes:
#      - ${PHPMYADMIN_DATA}:/data
#    networks:
#      - moodle

networks:
  internal:
    name: ${PROJECT_NAME}_network
    
#volumes:
#  mariadb_data:
#    driver: local
