version: "2"

services:

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    environment:
      - VIRTUAL_HOST=PORTAINER_SUBDOMAIN
      - VIRTUAL_PORT=PORTAINER_PORT
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data

#volumes:
#  portainer_data: