version: "3.9"

services:

    # WORDPRESS
    wordpress:
        container_name: wordpress_${PROJECT_NAME}
        image: wordpress:php${PHP_VERSION}-apache
        restart: always
        stdin_open: true
        tty: true
        #hostname: ${PROJECT_DOMAIN}
        ports:
            - ${WP_PORT}:80
        environment:
            WORDPRESS_DB_HOST: mysql
            WORDPRESS_DB_USER: ${MYSQL_USER}
            WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
            WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
            WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
        volumes:
            - ${WWW_DATA_DIR}:/var/www/html
        networks:
            - internal

    # DATABASES    
    mysql:
        container_name: mariadb_${PROJECT_NAME}
        image: mariadb
        restart: always
        command: --max_allowed_packet=256M
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_RANDOM_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        volumes:
            - ${MYSQL_DATA_DIR}:/var/lib/mysql
        networks:
            - internal

    # WP-CLI
    wordpress-cli:
        container_name: wpcli_${PROJECT_NAME}
        depends_on:
        - mysql
        - wordpress
        image: wordpress:cli
        # vstm: This is required to run wordpress-cli with the same user-id as wordpress. 
        user: xfs
        # vstm: add shared volume
        volumes:
        - ${WWW_DATA_DIR}:/var/www/html
    
    # PHPMYADMIN
    phpmyadmin:
        container_name: phpmyadmin_${PROJECT_NAME}
        image: phpmyadmin/phpmyadmin
        ports:
        - ${PHPMYADMIN_PORT}:80
        hostname: ${PHPMYADMIN_DOMAIN}
        environment:
            PMA_HOST: mysql
            PMA_USER: ${MYSQL_USER}
            PMA_PASSWORD: ${MYSQL_PASSWORD} 
        restart: always
        networks:
            - internal

networks:
  internal:
    name: network_${PROJECT_NAME}
    driver: bridge
#    external: true

#volumes:
#    db_data:
#    wordpress_data: